export enum State {
    MATCH, RESULTS, ALLIANCE_SELECTION, AWARDS, ADVANCEMENTS, BANNER
}

export enum MatchState {
    PREVIEW, SHOW_MATCH, AUTO, AUTO_END, TRANSITION, TELEOP, ENDGAME, FINISHED, ABORTED
}

export enum ResultsState {
    BASE, UP_NEXT
}

export enum BannerState {
    TEXT, ALLIANCE_SELECTION, AWARDS, ADVANCEMENTS
}